### ISSUE TITLE
Readme not making sense...

### ISSUE THREAD

**Issue by colinrgodsey** [lihaoyi/workbench#17]
/quote You can replace fullOptJs in the built.sbt file with fastOptJS, and swapping the reference to client-opt.js to client-fastopt.js, if you want to speed up the development cycle.

Im not sure where one would change the 'reference', and as far as I can tell it is hard coded in the plugin here:

https://github.com/lihaoyi/workbench/blob/0fae432ed016499aa1e290a3518fcd7ca5d91832/src/main/scala/workbench/Server.scala#L104

Is there any other way, or do we just have to use the client-opt.js ?

**Comment by sjrd** [comment]
That is the client part of the Workbench itself (because Workbench is itself written in Scala.js), which is part of the resources of Workbench. This is not the code of your application. Your application code, whether it's -fastopt or -opt, is served as "Any other GET request" here: https://github.com/lihaoyi/workbench/blob/0fae432ed016499aa1e290a3518fcd7ca5d91832/src/main/scala/workbench/Server.scala#L115
So the references you need to change are in your index.html file, typically.

**Comment by colinrgodsey** [comment]
erp, right, makes sense.

thanks!
